{% set name = "eefolium" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 040e1deae7e373fe94c148f6d0e5257731d92b3b2717be1cb666397cb4de1278

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - earthengine-api
    - folium >=0.11.0
    - python

test:
  imports:
    - eefolium

about:
  home: https://github.com/giswqs/eefolium
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A lightweight Python package for interactive mapping with Google Earth Engine and folium
  doc_url: https://giswqs.github.io/eefolium
  dev_url: https://github.com/giswqs/eefolium

extra:
  recipe-maintainers:
    - giswqs
