{% set name = "eefolium" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ed8bea9770bb45f5856ecc3f75b3f7eb8a5e38acfc319d1c605027f8e4896c72

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - earthengine-api
    - folium >=0.11.0
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - eefolium

about:
  home: https://github.com/giswqs/eefolium
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A lightweight Python package for interactive mapping with Google Earth Engine and folium
  doc_url: https://giswqs.github.io/eefolium
  dev_url: https://github.com/giswqs/eefolium

extra:
  recipe-maintainers:
    - giswqs
